"use client";
import "./globals.scss";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";

export const metadata = {
  title: "Online Account Opening Portal",
  description: "Generated by create next app",
};

export default function RootLayout({ children, isVisible, onClose }) {
  return (
    <html lang="en">
      <body
        className="fixed inset-0 bg-black bg-opacity-25 backdrop-blur-sm flex justify-center items-center"
        onClick={() => onClose()}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
