"use client";
import "./globals.scss";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import Newpage from "./components/Newpage";

export const metadata = {
  title: "Online Account Opening Portal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Newpage />
        <Footer />
      </body>
    </html>
  );
}
